"""
Django settings for NZTA_main_config project.
Generated by 'django-admin startproject' using Django 4.2.5.
"""

import os
from pathlib import Path

# translation setting
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-o--7eon6m(9q2r*(j0hw87%wcqr80p@qkxdxgxtgopt&c6^r88"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    # my app
    "content.apps.ContentConfig",
    "debug_toolbar",
]

# middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # languages
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # debug toolbar
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "NZTA_main_config.urls"

# template render config
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
            ],
        },
    },
]

# wsgi app
WSGI_APPLICATION = "NZTA_main_config.wsgi.application"

# Database, DISABLED
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
# Password validation, DISABLED
AUTH_PASSWORD_VALIDATORS = []

# Caches
CACHE_LIFI_TIME = 86400

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
# for prod use static root
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static/"),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static/")


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Internationalization/Languages config
LANGUAGE_CODE = "ru"
TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_TZ = True

# debug-toolbar
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]


